-- ════════════════════════════════════════════════════════════════════════════
--  Zx7 Hub — Supabase database setup
--  Paste this whole file into Supabase → SQL Editor → New query → Run.
--  Safe to run more than once.
-- ════════════════════════════════════════════════════════════════════════════

-- ── Members ─────────────────────────────────────────────────────────────────
create table if not exists public.members (
  id                bigint generated by default as identity primary key,
  member_code       text,
  username          text not null,
  password_hash     text not null,
  role              text not null default 'member',       -- member | r4 | admin
  approved          boolean not null default false,
  profession        text default 'engineer',              -- engineer | warLeader
  language          text default 'en',
  power             bigint default 0,
  join_date         date default current_date,
  security_question text,
  security_answer   text,
  signup_count      integer default 0,
  attendance_count  integer default 0,
  disabled          boolean default false,
  created_at        timestamptz default now()
);
create unique index if not exists members_username_lower_idx on public.members (lower(username));

-- ── Canyon Storm sign-ups ───────────────────────────────────────────────────
create table if not exists public.canyon_signups (
  id              bigint generated by default as identity primary key,
  member_id       bigint not null references public.members(id) on delete cascade,
  week_start      date not null,          -- the Thursday battle date for this cycle
  battle_date     date,
  power           text,
  squad_type      text,
  availability    text,                   -- confirmed | sub | cantMake
  time_preference text,                   -- either | time12 | time23
  can_flex_time   text,                   -- yes | no
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  unique (member_id, week_start)
);

-- ── Desert Storm sign-ups ───────────────────────────────────────────────────
create table if not exists public.desert_signups (
  id              bigint generated by default as identity primary key,
  member_id       bigint not null references public.members(id) on delete cascade,
  week_start      date not null,          -- the Friday battle date for this cycle
  battle_date     date,
  power           text,
  squad_type      text,
  availability    text,
  time_preference text,                   -- either | time18 | time23
  can_flex_time   text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  unique (member_id, week_start)
);

-- ── Saved storm teams (one row per storm per battle date) ───────────────────
create table if not exists public.battle_teams (
  id          bigint generated by default as identity primary key,
  type        text not null,              -- canyon | desert
  battle_date date not null,
  week_start  date,
  time_a      text,
  time_b      text,
  team_data   jsonb default '{}'::jsonb,
  updated_at  timestamptz default now(),
  unique (type, battle_date)
);

-- ── Storm sign-up switches (open/closed, season on/off) ─────────────────────
create table if not exists public.storm_settings (
  type          text primary key,         -- canyon | desert
  signups_open  boolean not null default false,
  season_active boolean not null default true,
  updated_at    timestamptz default now()
);
insert into public.storm_settings (type) values ('canyon'), ('desert')
on conflict (type) do nothing;

-- ── Upcoming battles (created automatically when teams are saved) ───────────
create table if not exists public.events (
  id             bigint generated by default as identity primary key,
  type           text,
  title          text,
  event_date     timestamptz,
  description    text,
  recurring      boolean default false,
  recurring_days integer,
  created_at     timestamptz default now()
);

-- ── Trains ──────────────────────────────────────────────────────────────────
create table if not exists public.trains (
  id           bigint generated by default as identity primary key,
  train_date   date not null unique,
  train_time   text,                      -- "14:00" server time
  week_start   date,
  conductor_id bigint references public.members(id) on delete set null,
  guardian_id  bigint references public.members(id) on delete set null,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create table if not exists public.train_goals (
  id         bigint generated by default as identity primary key,
  week_start date not null,
  goal       text,
  created_at timestamptz default now()
);

-- ── App-wide settings (weekly VS goal lives here) ────────────────────────────
create table if not exists public.app_settings (
  key        text primary key,
  value      text,
  updated_at timestamptz default now()
);
insert into public.app_settings (key, value) values ('vs_mode', 'PUSH')
on conflict (key) do nothing;

-- ── Access rules ────────────────────────────────────────────────────────────
-- Same model as ZpA Hub: the app signs people in itself, so the website's
-- public key needs read/write access to these tables.
do $$
declare t text;
begin
  foreach t in array array['members','canyon_signups','desert_signups','battle_teams',
                           'storm_settings','events','trains','train_goals','app_settings']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "zx7 app access" on public.%I', t);
    execute format('create policy "zx7 app access" on public.%I for all to anon, authenticated using (true) with check (true)', t);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ── Live updates (so changes show up without refreshing) ────────────────────
do $$
declare t text;
begin
  foreach t in array array['members','canyon_signups','desert_signups','storm_settings',
                           'events','trains','train_goals','app_settings']
  loop
    if not exists (select 1 from pg_publication_tables
                   where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
-- Deletes need the old row's details for live updates to remove it on screen
alter table public.canyon_signups replica identity full;
alter table public.desert_signups replica identity full;
